import os


class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv(
        'SQLALCHEMY_DATABASE_URI', 'sqlite:///:memory:')
    SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv(
        'SQLALCHEMY_TRACK_MODIFICATIONS', False)
    GEOLOCATION_DEFAULT_LATITUDE = os.getenv(
        'GEOLOCATION_DEFAULT_LATITUDE', 23.26)
    GEOLOCATION_DEFAULT_LONGTITUDE = os.getenv(
        'GEOLOCATION_DEFAULT_LONGTITUDE', 121)
